# Functions and Libraries

## Functions

methods or functions are blocks of code that are only executed when called

All methods are defined using snake_case

Methods can take arguments (or parameters) that we "pass in" separated by a comma

All methods are declared using the def keyword

The return keyword indicates whether the function should return a value (useful if assigning to a variable)

In [1]:
def say_hello(name: str):
    print('hello ' + name + '!')


say_hello('Amber')
say_hello('Carlo')

def add(a: int, b: int):
    return a + b

result: int = add(5, 10)

print(result)


# talk about all the bad ideas python has when talkin' 'bout functions

# default  value

def say_hello_v2(name = "Amber"):
  print("Hi! My name is " + name)

say_hello_v2('Ken')
say_hello_v2()


#declare constant instead

# variable variables key value pairs
def dog_names(dog2, dog3, dog1):
  print("Who's a good boi? you are " + dog1)

dog_names(dog1 = "Ule", dog2 = "Idaho", dog3 = "Ossi")

#this just creates confusion really

#unknown number of parameters
def horrible_children(*kids):
  print("The most horrible child is " + kids[1])

horrible_children("Emil", "Tobias")

def best_children(kids):
    print('the nicest child is ' + kids[-1])

kids=['emil', 'Linus']          
best_children(kids)

# just use a list or figure out what you are doing first ;)

# RECURSION

def recursion(k: int):
  if(k > 0):
    print(k)
    result = k + recursion(k - 1)
    print(f'{result}')
  else:
    result = 0
  return result


recursion(6)


# avoid tail recursion infinite loop

hello Amber!
hello Carlo!
15
Hi! My name is Ken
Hi! My name is Amber
Who's a good boi? you are Ule
The most horrible child is Tobias
the nicest child is Linus
6
5
4
3
2
1
1
3
6
10
15
21


21

## Libraries

Libraries are collections of functions that can be imported (as we did before) into another file and used.

One of python strengths, is the library ecosystem, which is vast and comprehensive.

Using 3rd party libraries saves us time and can even help us fill in some gaps in our own expertise.

It is important to learn how to use libraries and how to understand what libraries do and how they work.

### The Repository
[The repo link](https://pypi.org/)

The Python Package Index (PyPI) is a repository of software for the Python programming language.

It also gives you links to the code and documentation of each package.

### The Package Manager

pip is the package installer for Python. You can use pip to install packages from the Python Package Index and other indexes.

Let's use it to install NumPy and import the library.

### Numpy

NumPy (Numerical Python) or np is a python library for the creation and manipulation of multidimensional arrays, matrices and the statistical/mathematical operation one might want to perform on them.

It is an essential package for python and data analysis that anybody is bound to encounter at one point or another in their journey. 



### Why NumPy

Numpy's core library are written in low level languages such as C/C++/Fortran allowing for faster than regular python operation on arrays and matrices.  It also generally makes np's data structures more memory efficient than their vanilla python counterparts.

It is highly compatible with most other data analysis libraries such as Pandas, as it is a de facto standard library in any project of this kind.



### Multidimensional Arrays

The most important object in the np library is probably the ndarry object. This is a multidimensional array object that acts as a fast container for large datasets.



#### Getting started with NumPy

In this example we install np using the pip installer. This could also be done via Conda and other python package managers so chose whichever suits your dev env best.

```python
# Install via Pip in terminal
pip install numpy
```

In [2]:
# import the library

import numpy as np

# The library will be accessible as np

# NdArrays (Multidimensional arrays)
# Random data 

data = np.random.randn(2, 3)    
# creates a 2 dimensional array with 3 random elements per dimensions

# find array dimensions
print (data.shape)
# output (2, 3)

# just number of dimensions
print(data.ndim)
# output: 2

# find type of data 
print(data.dtype)
# output: float64

# make array from list 
list1 = [1, 4, 3, 8]

arr1 = np.array(list1)
print(arr1)
# output:  [1 4 3 8]

# nested lists are converted to multidimensional arrays
# note they need to be same length
list2 = [[1, 4, 3, 8], [48, 9, 39, 3]]
arr2 = np.array(list2)
print(arr2)
# output:  [[ 1  4  3  8][48  9 39  3]] 

print(arr2.ndim)
# output: 2

# create array and fill with 0s
zeros = np.zeros(5)
print (zeros)
# [0. 0. 0. 0. 0.]

# create array and fill with 1s
ones = np.ones(5)
print (ones)
# [1. 1. 1. 1. 1.]

# add dimensions 

zeros2D = np.zeros((5, 2))
print (zeros2D) 
# [[0. 0.]
#  [0. 0.]
#  [0. 0.]
#  [0. 0.]
#  [0. 0.]]

# create array of sequential numbers in range
seq = np.arange(10)
print (seq)
# [0 1 2 3 4 5 6 7 8 9]


# specify data type
arrWType = np.array([1, 2, 3], dtype=np.float64)
print (arrWType.dtype)
# float64

# cast array 
arrWDiffType = arrWType.astype(np.int32)
print (arrWDiffType.dtype)
# int32 

(2, 3)
2
float64
[1 4 3 8]
[[ 1  4  3  8]
 [48  9 39  3]]
2
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[0 1 2 3 4 5 6 7 8 9]
float64
int32


### NumPy Arithmetic operations

In [3]:
# arr1 [1 4 3 8]
sum = arr1 + arr1 
print (sum)
#[ 2  8  6 16]

times = arr1 * arr1 
print (times)
#[ 1 16  9 64]

minus = arr1 - arr1 
print (minus)
#[0 0 0 0]

div = arr1 / arr1
print (div)
#[1. 1. 1. 1.]

ex = np.exp(arr1)
print (ex)
# [2.71828183e+00 5.45981500e+01 2.00855369e+01 2.98095799e+03]

sqrt = np.sqrt(ex)
print (sqrt)
# [ 1.64872127  7.3890561   4.48168907 54.59815003]

[ 2  8  6 16]
[ 1 16  9 64]
[0 0 0 0]
[1. 1. 1. 1.]
[2.71828183e+00 5.45981500e+01 2.00855369e+01 2.98095799e+03]
[ 1.64872127  7.3890561   4.48168907 54.59815003]


### Indexing, Slicing and copying

In [4]:
print (arr1[2])
# 3

print (arr1[2:4])
# [3 8]

# avoid aliasing by using .copy()
sli = arr1[0:2].copy()
print (sli)
# [1 4]

sli[0] = 12
print (sli)
# [12  4]

print (arr1)
# [1 4 3 8]

# no aliasing

3
[3 8]
[1 4]
[12  4]
[1 4 3 8]


### Transposing and reshaping 

In [5]:
tr = np.arange(10).reshape(2,5)
# create array of 10 el 0 to 9 and reshape into a 2d array of 5 el
print (tr)
# [[0 1 2 3 4]
#  [5 6 7 8 9]]


# invert axis
print (tr.T)
# [[0 5]
#  [1 6]
#  [2 7]
#  [3 8]
#  [4 9]]

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
